### ISSUE TITLE
bootloops due to OOM(?)

### ISSUE THREAD

**Issue by afharo** [NicoIIT/esphome-components#29]
Hi! Thanks for this awesome project.

I've been using it for a long time, but recently, I noticed that my ESP32 WROOM-32D crashes very often and leads to weird behavior: some lights turn on when they shouldn't, the controls are momentarily unresponsive, ...

I thought that it was caused by not having updated the flash image and running the latest ESPHome server... 
However, after creating a new fresher build, the bootloops are quite obvious 😢 

Here are the logs previous to the crash (it repeats a few times until it goes into safe-boot mode):

```
[11:18:25][D][ble_adv_handler:347]: request stop advertising - 2
[11:18:25][D][ble_adv_handler:347]: request stop advertising - 3
[11:18:25][C][ble_adv_controller:033]: BleAdvController 'cuarto_de_juegos_fanlamp'
[11:18:25][C][ble_adv_controller:034]:   Hash ID '4C6F8007'
[11:18:25][C][ble_adv_controller:035]:   Index '0'
[11:18:25][C][ble_adv_controller:036]:   Transmission Min Duration: 500 ms
[11:18:25][C][ble_adv_controller:037]:   Transmission Max Duration: 1000 ms
[11:18:25][C][ble_adv_controller:038]:   Transmission Sequencing Duration: 100 ms
[11:18:25][D][ble_adv_handler:340]: request start advertising - 5: 02.01.19.1B.03.77.F8.B6.5F.2B.5E.00.FC.31.51.10.D8.98.08.24.0A.7B.FC.38.C1.9B.37.16.72.C1.F7 (31)
[11:18:25][D][ble_adv_handler:340]: request start advertising - 6: 02.01.19.1B.03.77.F8.B6.5F.2B.5E.00.FC.31.51.10.83.96.08.24.0A.7B.FC.82.8E.4E.78.55.DA.8E.3F (31)
[11:18:25]
[11:18:25]abort() was called at PC 0x401f967b on core 1
[11:18:25]
[11:18:25]
[11:18:25]Backtrace:0x40083751:0x3ffcd7200x40093129:0x3ffcd740 0x400986ed:0x3ffcd760 0x401f967b:0x3ffcd7e0 0x401f96c2:0x3ffcd800 0x401f97bb:0x3ffcd820 0x401f971a:0x3ffcd840 0x401f9825:0x3ffcd860 0x401fd6f7:0x3ffcd880 0x401036c9:0x3ffcd8d0 0x400df5fb:0x3ffcd910 0x400df606:0x3ffcd930 0x40214875:0x3ffcd950 0x402148d9:0x3ffcd970 0x400f36e5:0x3ffcd990 0x400f837e:0x3ffcd9c0 0x40106111:0x3ffcd9e0 
```

<details><summary>Here's my config, in case there's something I need to improve</summary>
<p>

```
substitutions:
  name: esphome-web-7f4b44
  friendly_name: Ceiling-fan controller

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

external_components:
  # shorthand
  source: github://NicoIIT/esphome-components
  # refresh: 0s

ble_adv_controller:
  # Despacho
  - id: despacho_fanlamp
    encoding: fanlamp_pro
    variant: v1
    duration: 500
    reversed: false
    forced_id: 0
  # Cuarto de los niños
  - id: cuarto_de_los_ninos_fanlamp
    encoding: fanlamp_pro
    variant: v1
    duration: 500
    reversed: false
    forced_id: 0
  # Cuarto de juegos
  - id: cuarto_de_juegos_fanlamp
    encoding: fanlamp_pro
    variant: v1
    duration: 500
    reversed: false
    forced_id: 0

light:
  # Despacho
  - platform: ble_adv_controller
    ble_adv_controller_id: despacho_fanlamp
    name: Despacho Fanlamp
  - platform: ble_adv_controller
    ble_adv_controller_id: despacho_fanlamp
    name: Despacho Fanlamp Luz Indirecta
    type: onoff
    index: 1
  # Cuarto de los niños
  - platform: ble_adv_controller
    ble_adv_controller_id: cuarto_de_los_ninos_fanlamp
    name: Cuarto de los Niños Fanlamp
  - platform: ble_adv_controller
    ble_adv_controller_id: cuarto_de_los_ninos_fanlamp
    name: Cuarto de los Niños Fanlamp Luz Indirecta
    type: onoff
    index: 1
  # Cuarto de juegos
  - platform: ble_adv_controller
    ble_adv_controller_id: cuarto_de_juegos_fanlamp
    name: Cuarto de juegos Fanlamp

fan:
  # Despacho
  - platform: ble_adv_controller
    ble_adv_controller_id: despacho_fanlamp
    name: Despacho Fresquito
    speed_count: 6
    use_direction: true
  # Cuarto de los niños
  - platform: ble_adv_controller
    ble_adv_controller_id: cuarto_de_los_ninos_fanlamp
    name: Cuarto de los Niños Fresquito
    speed_count: 6
    use_direction: true
  # Cuarto de juegos
  - platform: ble_adv_controller
    ble_adv_controller_id: cuarto_de_juegos_fanlamp
    name: Cuarto de juegos Fresquito
    speed_count: 6
    use_direction: true

button:
  # Despacho
  - platform: template
    entity_category: config         # only if you want to have the button in the 'Configuration' part in HA
    name: Pair Despacho Fanlamp
    on_press:
      ble_adv_controller.pair: despacho_fanlamp
  # Cuarto de los niños
  - platform: template
    entity_category: config         # only if you want to have the button in the 'Configuration' part in HA
    name: Pair Cuarto de los Niños Fanlamp
    on_press:
      ble_adv_controller.pair: cuarto_de_los_ninos_fanlamp
  # Cuarto de juegos
  - platform: template
    entity_category: config         # only if you want to have the button in the 'Configuration' part in HA
    name: Pair Cuarto de juegos Fanlamp
    on_press:
      ble_adv_controller.pair: cuarto_de_juegos_fanlamp

# Report WiFi connection stats
# sensor:
#   - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
#     name: "WiFi Signal dB"
#     id: wifi_signal_db
#     update_interval: 60s
#     entity_category: "diagnostic"

#   - platform: copy # Reports the WiFi signal strength in %
#     source_id: wifi_signal_db
#     name: "WiFi Signal Percent"
#     filters:
#       - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
#     unit_of_measurement: "Signal %"
#     entity_category: "diagnostic"
#     device_class: ""
```

</p>
</details> 

Any ideas of what I can do?

Thank you!

**Comment by NicoIIT** [comment]
Well you are giving hard time to your ESP !!!! I think you simply have too many components, in particular the web server + ble is maybe too much!

Still you can try to [deactivate the scan](https://github.com/NicoIIT/esphome-components/blob/main/components/ble_adv_handler/README.md#variables) (as you do not use ble_adv_remote and that the components are already configured), and setup the log level as INFO, this will probably help:

```yaml
logger:
  level: INFO

ble_adv_handler:
  scan_activated: false
```

If you still have issues, or just because it is easier to config,  you can migrate to the [HA Component](https://github.com/NicoIIT/ha-ble-adv) (immediately if your HA host is Linux based, supports bluetooth and your devices are in its range OR in a few hours if you can wait for the [ble_adv_proxy](https://github.com/NicoIIT/ha-ble-adv/issues/11) delivery)
